# -*- coding: utf-8 -*-
"""Taller_Regresion_Multiple_Claro-Juan_David_Sierra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v2ROtkfoCDubpLE2PFzG48-RQWoFGB4u

# Taller (Colab) — Regresión lineal múltiple: coeficientes, significancia y residuales

**Duración sugerida:** 50–60 min de trabajo + sustentación.

## Qué se evalúa hoy
1) **Interpretación de coeficientes** en regresión múltiple (cambio marginal, controlando por, unidades).
2) **Significancia por coeficiente** (t y p-valor, y coherencia con el IC).
3) **Lectura de residuales** (qué dicen y qué alertas sugieren).

---
## Definiciones mínimas (úsalas textual en la sustentación)

### A. Interpretación correcta de un coeficiente (plantilla obligatoria)
Para un predictor Xj:
> “Si Xj aumenta en **1 unidad**, la **nota esperada** cambia en **β̂j** puntos, **manteniendo constantes** los demás predictores del modelo.”

**Siempre debes mencionar:**
- signo (sube/baja),
- magnitud (cuánto),
- unidad (puntos de nota por unidad de Xj),
- y la frase “manteniendo constantes …”.

### B. Significancia (por coeficiente)
- Hipótesis: H0: βj = 0 vs H1: βj ≠ 0.
- t = β̂j / SE(β̂j).
- p-valor: evidencia contra H0 bajo los supuestos del modelo.

### C. Residuales (qué mirar)
- Residual = observado − predicho.
- Si hay patrón (curva/abanico) en residuales vs predichos → posible problema (no linealidad/heterocedasticidad).
- Outliers: residuales muy grandes en valor absoluto.
"""

# 0) LIBRERÍAS (NO MODIFICAR)
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm

np.random.seed(2026)
pd.set_option('display.precision', 4)

"""## Contexto y variables (común para todos)

**Unidad:** estudiante.

**Y:** `nota` (0 a 5)

**X:**
- `horas` = horas de estudio por semana
- `asistencia` = porcentaje de asistencia (0–100)
- `promedio` = promedio previo (0–5)

"""

# 1) SIMULACIÓN BASE (NO MODIFICAR)
n = 300
np.random.seed(2026)

promedio = np.clip(np.random.normal(3.5, 0.5, n), 0, 5)
asistencia = 70 + 8*(promedio-3.5) + np.random.normal(0, 10, n)
asistencia = np.clip(asistencia, 40, 100)
horas = 6 + 2.0*(promedio-3.5) + 0.05*(asistencia-70) + np.random.normal(0, 2.5, n)
horas = np.clip(horas, 0, 25)

eps = np.random.normal(0, 0.35, n)
nota = 0.6 + 0.05*horas + 0.012*asistencia + 0.55*promedio + eps
nota = np.clip(nota, 0, 5)

df = pd.DataFrame({'nota': nota, 'horas': horas, 'asistencia': asistencia, 'promedio': promedio})
df.head()

"""# Instrucciones del taller (USTEDES escriben el código)

## Entrega: 3 cosas
1) Tu notebook con el código.
2) Un párrafo final (8–10 líneas).
3) 2 gráficas guardadas en el notebook.

---
## Tareas (claras y numeradas)

### Parte 1 — Ajuste del modelo y coeficientes (interpretación)
1. Ajusta el modelo **M3**: `nota ~ horas + asistencia + promedio`.
2. Copia (o muestra) la tabla de coeficientes.
3. Interpreta **cada** coeficiente (horas, asistencia, promedio) con la **plantilla obligatoria**.
   - incluye signo, magnitud, unidad y “manteniendo constantes …”.
4. Interpreta el efecto de **+5 horas** usando el coeficiente de `horas`.

### Parte 2 — Significancia (por coeficiente)
5. Para cada predictor (horas, asistencia, promedio), responde:
   - H0 y H1.
   - p-valor: ¿rechazas H0 al 5%?
   - IC 95%: ¿incluye 0 o no?
   - Cierra con 1 frase: “significativo” NO es lo mismo que “importante”.

### Parte 3 — Residuales (lectura rápida y profesional)
6. Calcula residuales y valores ajustados (predichos).
7. Haz estas 2 gráficas:
   - (G1) Residuales vs Ajustados (scatter) + línea horizontal en 0.
   - (G2) Histograma de residuales (o QQ plot si sabes hacerlo).
8. Escribe 3 bullets:
   - ¿ves patrón (curva/abanico) o se ve “nube” alrededor de 0?
   - ¿hay outliers evidentes?
   - ¿qué supuesto podría fallar si ves abanico?

### Parte 4 — Modificación obligatoria (para forzar nueva interpretación)
Vamos a cambiar UNIDAD de una variable y a crear un nuevo modelo.
9. Crea `horas10 = horas / 10` y ajusta el modelo **M3b**: `nota ~ horas10 + asistencia + promedio`.
10. Compara β̂_horas (M3) vs β̂_horas10 (M3b) y escribe:
   - ¿por qué cambia el número?
   - ¿cómo cambia la interpretación en palabras?

---
## Párrafo final (8–10 líneas)
Incluye:
- interpretación correcta de los 3 coeficientes (resumida),
- 1 conclusión sobre significancia (sin exagerar causalidad),
- 1 conclusión sobre residuales,
- y 1 línea sobre el cambio de unidades (horas a decenas de horas).

"""

# =====================================================
# ESPACIO DE TRABAJO — ESCRIBE AQUÍ TU SOLUCIÓN

# 1. Preparación de los datos
# Asumiendo que tu DataFrame se llama 'df'
# Definimos X (variables independientes) e y (variable a predecir)
"""X = df[['horas', 'asistencia', 'promedio']]
y = df['nota']

# IMPORTANTE: Agregar la constante para el intercepto
X = sm.add_constant(X)

# 2. Creación y ajuste del modelo
modelo_m3 = sm.OLS(y, X).fit()

# 3. Desplegar los resultados
print(modelo_m3.summary())"""
# =====================================================

# TIP para ajustar:
X = sm.add_constant(df[['horas','asistencia','promedio']])
m3 = sm.OLS(df['nota'], X).fit()
print(m3.summary())

# 1) Ajusta M3

# 2) Interpreta coeficientes
# Nos podemos dar cuenta que la variable que mas efecto tiene en el resultado final o en la nota esperada es el promedio previo del estudiante, ya que si se mantiene constantes
# Las demas variables, y se aumenta en una unidad el promedio, la nota esperada cambia en 0.5753 puntos. Por otro lado la variable que le sigue es las horas que dedico por semana
# ya que si las demas se mantienen constantes y las horas aumentan en una unidad, entonces, la nota esperada cambia en 0.0412. Con esto nos queda la variable asistencia.
# Si el estudiante aumentara en 5 unidades su estudio por semana entonces su nota esperada cambiaria en 0.2060 puntos.
# 3) Significancia + IC

# 4) Residuales + gráficas

# 5) Modelo con horas10 y comparación

pass

"""# Parte 1
Nos podemos dar cuenta que la variable que mas efecto tiene en el resultado final o en la nota esperada es el promedio previo del estudiante, ya que si se mantiene constantes, las demas variables, y se aumenta en una unidad el promedio, la nota esperada cambia en 0.5753 puntos. Por otro lado la variable que le sigue es las horas que dedico por semana ya que si las demas se mantienen constantes y las horas aumentan en una unidad, entonces, la nota esperada cambia en 0.0412. Con esto nos queda la variable asistencia.

Si el estudiante aumentara en 5 unidades su estudio por semana entonces su nota esperada cambiaria en 0.2060 puntos.

# Parte 2

Para el contexto de esta regresion lineal, las hipotesis que podemos encontrar son las siguientes:

Para cada variable $j$ (horas, asistencia, promedio), se plantea:

$$
H_0: \beta_j = 0
$$
> **Interpretación:** La variable no tiene un efecto lineal sobre la nota (no es significativa).

$$
H_1: \beta_j \neq 0
$$
> **Interpretación:** La variable tiene un efecto lineal sobre la nota (es estadísticamente significativa).

**Regla de decisión:** Si el $p\text{-valor} < 0.05$, rechazamos $H_0$.

Luego de esto revisamos el resultante de cada valor-p de las variables, se decide rechazar la hipotesis nula para cada variable.

Por otro lado, cada intervalo de confianza de las variables no incluyen al 0, todos son positivos, por tanto las variables son significativamente positivas.

Podemos concluir que aunque todas las variables son significativas para la nota esperada del estudiante, no todas son igual de importantes y no influyen en la misma medida al resultado final.
"""

X = df[['horas', 'asistencia', 'promedio']]
y = df['nota']

# 2. Agregar la columna de constante (obligatorio en statsmodels.api)
X = sm.add_constant(X)

# 3. Ajustar el modelo OLS
modelo_m3 = sm.OLS(y, X).fit()

# --- A partir de aquí tu código original ya funcionará ---
df['ajustados'] = modelo_m3.fittedvalues
df['residuales'] = modelo_m3.resid

# 6. Calcular valores ajustados (predichos) y residuales
df['ajustados'] = modelo_m3.fittedvalues
df['residuales'] = modelo_m3.resid

# 7. Graficar
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

# (G1) Residuales vs Ajustados
ax1.scatter(df['ajustados'], df['residuales'], alpha=0.5, color='teal')
ax1.axhline(y=0, color='red', linestyle='--')
ax1.set_title('Residuales vs Valores Ajustados')
ax1.set_xlabel('Valores Ajustados (Predicciones)')
ax1.set_ylabel('Residuales')

# (G2) Histograma de Residuales
ax2.hist(df['residuales'], bins=20, color='#FF71CE', edgecolor='#01CDFE', linewidth=1.2)
ax2.set_title('Distribución de los Residuales')
ax2.set_xlabel('Valor del Residual')
ax2.set_ylabel('Frecuencia')

plt.tight_layout()
plt.show()

"""# Parte 3

En la gráfica de dispersión se observa claramente una nube de puntos distribuida de forma aleatoria alrededor del eje cero. No hay evidencia de patrones curvos (que sugerirían relaciones no lineales) ni de tendencias sistemáticas.

No se detectan outliers extremos que distorsionen el modelo. Aunque hay un par de puntos con residuales ligeramente superiores a 1.0 o inferiores a -1.0, se integran dentro de la estructura general de la distribución normal y no se alejan drásticamente de la masa principal de datos.

Por ultimo, si los puntos mostraran una apertura en forma de abanico (mayor dispersión a medida que aumentan los valores ajustados), fallaría el supuesto de homocedasticidad.
# Verificar mas formas de verificacion de los supuestos, profundizar mas en los supuestos

# Supuesto de la Normalidad
"""

# 1. Gráfica QQ-Plot (Para verificar Normalidad)
# El parámetro line='45' dibuja la referencia ideal
fig_qq = sm.qqplot(df['residuales'], line='45', fit=True)
plt.title('Gráfico QQ de los Residuales')
plt.grid(True, alpha=0.3)
plt.show()

"""# Supuesto de Linealidad"""

# 2. Gráficas de Linealidad (Residuales Parciales)
# Esto muestra cómo se comporta cada variable individualmente frente a la nota
fig = plt.figure(figsize=(12, 8))
sm.graphics.plot_partregress_grid(modelo_m3, fig=fig)
plt.tight_layout()
plt.show()

"""# Supuesto de no multicolinealidad"""

from statsmodels.stats.outliers_influence import variance_inflation_factor

# 1. Seleccionamos las variables independientes (incluyendo la constante)
X = modelo_m3.model.exog
# 2. Calculamos el VIF para cada columna
vif_data = pd.DataFrame()
vif_data["Variable"] = modelo_m3.model.exog_names
vif_data["VIF"] = [variance_inflation_factor(X, i) for i in range(X.shape[1])]

print(vif_data)

"""# Parte 4


"""

# Crear la variable escalada
df['horas10'] = df['horas'] / 10

# Definir predictores para el nuevo modelo (incluyendo la constante)
X_b = df[['horas10', 'asistencia', 'promedio']]
X_b = sm.add_constant(X_b)

# Ajustar el modelo M3b
modelo_m3b = sm.OLS(df['nota'], X_b).fit()

# Comparar coeficientes
print("Coeficiente horas (M3):", modelo_m3.params['horas'])
print("Coeficiente horas10 (M3b):", modelo_m3b.params['horas10'])

"""Aqui nos podemos dar cuenta de que el coeficiente M3B es 10 veces mas grande que el otro coeficiente ya que ahora la variable explicativa es multiplicada por 10, Lo que nos cambia la interpretacion a que ahora por cada 10 horas estudiadas, la nota aumenta en $\beta$ puntos.

El modelo indica que las horas, la asistencia y el promedio tienen una asociación positiva y significativa con la nota ($p < 0.05$), con incrementos promedio de 0.041, 0.011 y 0.575 puntos por cada unidad adicional, respectivamente. El diagnóstico de residuales confirma el cumplimiento de los supuestos de normalidad y homocedasticidad al presentar una distribución aleatoria sin patrones de dependencia (Durbin-Watson = 1.934). Finalmente, al utilizar decenas de horas (horas10), el coeficiente aumenta diez veces ($\beta \approx 0.41$) para reflejar el impacto de un bloque de tiempo mayor, manteniendo intacta la validez y el ajuste del modelo ($R^2 = 0.543$).
"""